### ISSUE TITLE
Consider adding commit messages

### ISSUE THREAD

**Issue by cptchuckles** [jlcrochet/vim-razor#5]
Thanks for maintaining this project.  It will prove very useful to me (and others) until one day when we collectively figure out how to get Omnisharp to process razor in a way that's not locked down to Microsoft products.

I included this plugin in my neovim config a few days ago using packer.nvim, which updates my plugins automatically and shows me the reflog for all new commits for all my plugins.  But I had to pop in to see what changed here a couple of hours ago because there was no commit message describing the change.  From the reflog, I gather that you don't normally like to bother, but I highly recommend taking up the practice, not only for others to see easily but also for your future self -- bisecting, reverting, merging etc. all become a lot clearer when the hashes have concise one-liners next to them!

**Comment by jlcrochet** [comment]
You're right: there are enough people using this plugin at this point that I should be more mindful of such things from now on. Thanks for the suggestion.
